
services:

  base_service:
    build: .
    working_dir: /app/
    volumes:
      - ./:/app/
    environment:
      - github_token
      - gitlab_token

  create_registry:
    extends:
      service: base_service
    command: python ./src/create_registry.py

  convert_to_clscor:
    extends:
      service: base_service
    command: python ./src/convert_to_clscor.py
