
services:
  veld_registry:
    build: .
    command: python -u /app/src/create_registry.py
    working_dir: /app/
    volumes:
      - ./src/:/app/src/
    environment:
      - github_token
      - gitlab_token

