
services:
  veld_registry:
    build: .
    command: python -u /app/src/create_registry.py
    working_dir: /app/
    volumes:
      - ./src/:/app/src/
      - ./data/:/app/in/
      - ./README.md:/app/out/README.md
    environment:
      - github_token
      - gitlab_token

